---
server:
  port: 8080
  contextPath: /rmportal
---
spring:
  profiles: local
datasource:
  rmportal:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: default
datasource:
  rmportal:
    url: jdbc:mysql://aae2919xc24v9s.czufkxkprcji.us-east-2.rds.amazonaws.com:3306/ebdb
    username: root
    password: root1234
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQL5Dialect
---
spring:
  profiles: dev
datasource:
  rmportal:
    url: jdbc:mysql://localhost:3306/rmportal?useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQL5Dialect
---
spring:
  profiles: prod
datasource:
  rmportal:
    url: jdbc:mysql://aae2919xc24v9s.czufkxkprcji.us-east-2.rds.amazonaws.com:3306/ebdb
    username: root
    password: root1234
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQL5Dialect
---      
logging:
  level:
    org.springframework.web: ERROR
    com.mkyong: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: E:/logs/application.log

